### ISSUE TITLE
openblas is not pinned

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/scikit-umfpack-feedstock#8]
```
>>> import scikits.umfpack
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/scikits/umfpack/__init__.py", line 12, in <module>
    from .umfpack import *
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/scikits/umfpack/umfpack.py", line 130, in <module>
    from . import _umfpack as _um
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/scikits/umfpack/_umfpack.py", line 28, in <module>
    __umfpack = swig_import_helper()
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/scikits/umfpack/_umfpack.py", line 24, in swig_import_helper
    _mod = imp.load_module('__umfpack', fp, pathname, description)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/scikits/umfpack/__umfpack.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libopenblas-r0.2.18.dylib
  Referenced from: /Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/scikits/umfpack/__umfpack.cpython-35m-darwin.so
  Reason: image not found
```

The reason is that I have `libopenblasp-r0.2.19.dylib` in my lib directory. Openblas needs to be pinned here. 

@scopatz do you know how to fix this?

**Comment by asmeurer** [comment]
Even if I downgrade openblas to 0.2.18, it fails because I have `libopenblasp-r0.2.18.dylib` (note the extra `p`).

**Comment by jakirkham** [comment]
`p` is for pthreads IIRC.

**Comment by grlee77** [comment]
I think this is likely that SuiteSparse changed to OpenBLAS 0.2.19 after these packages were built.  Only the Python 3.6 packages were probably built against the latest SuiteSparse so I should bump the build number so the older Python versions get updated packages as well.

@jakirkham 
To be safe should this recipe also pin OpenBLAS as it depends on SuiteSparse which pins it?  I don't know how else to prevent these from getting out of sync again in the future?

**Comment by grlee77** [comment]
It is likely that scikit-sparse-feedstock has this same problem, but at the moment it is in sync because a newer release was built more recently than SuiteSparse.

**Comment by jakirkham** [comment]
> To be safe should this recipe also pin OpenBLAS as it depends on SuiteSparse which pins it? I don't know how else to prevent these from getting out of sync again in the future?

Given as it seems to be linking to it directly, this seems totally reasonable. Unfortunate that it does that though. 😕

FWIW we never build 0.2.19 without pthreads. So you don't need to worry about that issue.

**Comment by asmeurer** [comment]
The conda-forge pinning tooling should be improved. Any package that links against a package with pinning should directly depend on it (with pinned versions).

**Comment by jakirkham** [comment]
Well, actually, we sort of agreed a while ago that this is something we wanted to see addressed in `conda-build` and they just did that with build customization.

xref: https://github.com/conda/conda-build/pull/1585

**Comment by asmeurer** [comment]
So with that PR would conda-build autopin openblas when the package links to it?

**Comment by jakirkham** [comment]
IIUC it would pin the run requirement based on the version used in build. Though we might need to add a configuration file to explain to `conda-build` how to pin `openblas` correctly. It would no longer require hard coding of a version number.

**Comment by jakirkham** [comment]
Here's the relevant [docs]( http://stuarteberg.github.io/conda-docs/building/variants.html ). I think they are *mostly* in sync with what got merged, but there might be a few small things that changed.

**Comment by grlee77** [comment]
I think this issue may be specific to OS X.  I see the same problem reported when import `scikit-umfpack` on a Macbook, but on a linux workstation the import works without error.

**Comment by jakirkham** [comment]
Interesting. Should we raise an issue with upstream?

**Comment by asmeurer** [comment]
So I'm unclear if it would solve this issue then. openblas needs to be pinned iff the package links against it. Packages that recursively depend on openblas don't necessarily need to pin it (like a pure Python package that depends on scipy).

**Comment by grlee77** [comment]
I think that is correct.  If I inspect the build log for #9 on CircleCI, I can see `-lopenblas` included in the gcc calls.  This was not the case for `scikit-sparse` so I have not made the same changes over there.  I think maybe that linking is not necessary on `scikit-umfpack`'s end.  will try to raise an issue there and see if they have a solution

**Comment by asmeurer** [comment]
`conda inspect linkages scikit-umfpack` will tell you what the package links against (or at least it's supposed to, for me right now it is raising AssertionError).

**Comment by grlee77** [comment]
requested feedback upstream at scikit-umfpack/scikit-umfpack#32

**Comment by grlee77** [comment]
@asmeurer 

On the OS X system where this fails to import I get:

```
12:51 $ conda inspect linkages scikit-umfpack
scikit-umfpack
--------------

conda-forge::suitesparse-4.5.3-blas_openblas_204:
    libamd.2.4.6.dylib (lib/libamd.2.4.6.dylib)
    libumfpack.5.7.6.dylib (lib/libumfpack.5.7.6.dylib)

system:
    libSystem.B.dylib (/usr/lib/libSystem.B.dylib)

not found:
    libopenblas-r0.2.18.dylib (not found)
```

where my conda is:
```
               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.5
         python version : 3.5.2.final.0
       requests version : 2.12.4
```

**Comment by asmeurer** [comment]
Yep, the `not found` indicates that the package is broken. conda-build/conda-forge ought to make it easier to test and fail recipes that end up this way. 

My point is that if you had a working package, it would say

```
openblas:
    libopenblas-r0.2.19.dylib (lib/libopenblas-r0.2.19.dylib)
```

and that would tell you that you are linking against openblas, and hence need to pin it.

**Comment by grlee77** [comment]
nice.  was not previously aware of that command.  Had just use `otool -L <.dylib>` in the past.

**Comment by grlee77** [comment]
just merged the pinning PR.  please test once they become available at anaconda.org
